- hosts: all
  gather_facts: yes
  vars:
   installPath: '/tmp/logTruncate.sh' #absolute path where script will be placed
   auxPath: '/tmp'          #Auxiliar path where logs will be moved to be compressed
   historyDays: '90'        #Accepted values: "false/[0,1,..]" (days value)
   minLogSize: '1'          #Accepted values: [0,1,..] (value in Bytes)

  #Apps managed by GII
   IHS: 'true'              #Accepted values: "true/false"
   WAS: 'true'              #Accepted values: "true/false"
   
   #Custom log paths
   logs:                    
     - path:      /var/log/boot.log
       wildcard:  /var/log/boot.log-????????

     - path:      /var/log/dmesg
       wildcard:  /var/log/dmesg.old-*

     - path:      /var/log/cron
       wildcard:  /var/log/cron-????????

     - path:      /fakepath #if path doesn't exists, its truncate options won't be installed
       wildcard:  /fakepathwildcard

  roles:                  
    - {role: logTruncate}
